# config.yaml
program: /workspace/index.py
method: bayes
name: NCL-yelp2018
run_cap: 500
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--model"
  - "NCL"
  - "--gpu_id"
  - "1"
  - "--dataset"
  - "yelp2018"
  - ${args}
metric:
  goal: maximize
  name: target
parameters:
  embbedding_size: 
    values: [16, 32, 64]
  # num_epochs:
  #   values: [5, 10, 15]
  batch_size: 
    values: [16,32,64]
  learning_rate:
    min: 0.0001
    max: 0.01
  lambda: 
    max: 0.01
    min: 0.0001
  batch_size: 
    values: [512, 1024, 2048]
  # model_config.num_layers: 
  #   max: 4
  #   min: 2
  # model_config.hyper_layers: 
  #   values: [1]
  model_config.ssl_reg:
    max: 0.001
    min: 0.000001
  model_config.proto_reg: 
    max: 0.0001
    min: 0.0000001
  model_config.temperature: 
    max: 0.9
    min: 0.05
  model_config.lambda: 
    max: 0.5
    min: 0.05
  model_config.num_clusters: 
    values: [1000,1500,2000]
