yelp2018:
  name: LightGCN
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
    - 50
  embedding_size: 64
  num_epochs: 120
  batch_size: 2048
  learning_rate: 0.001
  lambda: 0.0001
  output: ./results/
  model_config.num_layers: 3


iFashion:
  name: LightGCN
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
    - 50
  embedding_size: 64
  num_epochs: 20
  batch_size: 2048
  learning_rate: 0.001
  lambda: 0.0001
  output: ./results/
  model_config.num_layers: 3

