iFashion:
  name: SGL
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
  embbedding_size: 64
  num_epochs: 20
  batch_size: 2048
  learning_rate: 0.001
  lambda: 0.0001
  output: ./results/
  # SGL config
  model_config:
    num_layers: 2
    lambda: 0.1
    droprate: 0.1
    augtype: 1
    temperature: 0.2

yelp2018:
  name: SGL
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
  embbedding_size: 64
  num_epochs: 20
  batch_size: 2048
  learning_rate: 0.001
  lambda: 0.0001
  output: ./results/
  # SGL config
  model_config:
    num_layers: 2
    lambda: 0.1
    droprate: 0.1
    augtype: 1
    temperature: 0.2
