yelp2018:
  name: SGL
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
  embbedding_size: 64
  num_epochs: 120
  batch_size: 2048
  learning_rate: 0.001
  lambda: 0.0001
  output: ./results/
  # SGL config
  model_config.droprate: 0.1
  model_config.augtype: 1
  model_config.temperature: 0.2
  model_config.num_layers: 3
  model_config.lambda: 0.1

iFashion:
  name: SGL
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
  embbedding_size: 64
  num_epochs: 20
  batch_size: 2048
  learning_rate: 0.001
  lambda: 0.0001
  output: ./results/
  # SGL config
  model_config.droprate: 0.1
  model_config.augtype: 1
  model_config.temperature: 0.2
  model_config.num_layers: 2
  model_config.lambda: 0.1
