yelp2018:
  name: XSimGCL
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
  embedding_size: 64
  num_epochs: 120
  batch_size: 2048
  learning_rate: 0.001
  lambda: 0.0001
  output: ./results/
  # model config
  model_config:
    num_layers: 2
    layer_cl: 1
    lambda: 0.2
    eps: 0.2
    tau: 0.15

iFashion:
  name: NCL
  seed: 12345
  type: graph
  ranking: 
    - 10
    - 20
  embedding_size: 64
  num_epochs: 120
  batch_size: 2048
  learning_rate: 0.001
  lambda: 0.0001
  output: ./results/
  # model config
  model_config.num_layers: 2
  model_config.layer_cl: 1
  model_config.lambda: 0.2
  model_config.eps: 0.2
  model_config.tau: 0.15
